// src/lib/ui/Breadcrumbs.svelte
<script lang="ts">
	import { page } from '$app/state';
	import { afterNavigate } from '$app/navigation';

	let breadcrumbs: { name: string; href: string }[] = [];

	function updateBreadcrumbs() {
		breadcrumbs = [...generateBreadcrumbs(page.url.pathname)];
	}

	function generateBreadcrumbs(pathname: string): { name: string; href: string }[] {
		const segments = pathname.split('/').filter(Boolean);
		return segments.map((segment, index) => ({
			name: segment.charAt(0).toUpperCase() + segment.slice(1),
			href: `/${segments.slice(0, index + 1).join('/')}`
		}));
	}

	updateBreadcrumbs();

	afterNavigate(updateBreadcrumbs);
</script>

<nav class="flex items-center justify-start gap-3 px-4 py-1.5 font-inter text-xs text-gray-500">
	{#if breadcrumbs.length === 0}
		<a href="/" class="outline-none ring-0">/</a>
	{/if}
	{#each breadcrumbs as crumb, i}
		{#if i == 0}
			<a href="/" class="outline-none ring-0">/</a>
		{/if}
		<a href={crumb.href} class="outline-none ring-0 hover:underline">
			{crumb.name}
		</a>
		<span>/</span>
	{/each}
</nav>

// src/app/_components/ui/breadcrumbs.tsx
"use client";

import Link from "next/link";
import { usePathname } from "next/navigation";

export default function Breadcrumbs() {
  const pathname = usePathname();
  const name = pathname.split("/").pop();
  if (!name) {
    return (
      <div className="bg-stone-50 font-rubik text-xs">
        <ol className="flex items-center justify-start gap-3 p-2 pl-4 text-neutral-500">
          <Link href="/">/</Link>
        </ol>
      </div>
    );
  }
  const capitalized = name.charAt(0).toUpperCase() + name.slice(1);

  return (
    <div className="bg-stone-50 font-rubik text-xs">
      <ol className="flex items-center justify-start gap-3 p-2 pl-4 text-neutral-500">
        <Link href="/">/</Link>
        <Link href={pathname}>{capitalized}</Link>
      </ol>
    </div>
  );
}
